apiVersion: apps/v1
kind: Deployment
metadata:
  name: datatonic
  labels:
    app: datatonic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datatonic
  template:
    metadata:
      labels:
        app: datatonic
    spec:
      containers:
      - name: datatonic
        image: iman88/devops-task:0.0.1
        ports:
        - containerPort: 80